config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # 장고에서 settings.py를 import할 때는 이와 같은 방식으로 한다.
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

# 개발 모드인지 확인하고, 파일을 제공한다. 아닌 경우는 보안상 하면 안돼
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # settings.MEDIA_URL(media)로 요청이 들어오면, settings.MEDIA_ROOT(/uploads)로 보낸다.

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    # path("", room_views.all_rooms, name="home"), # not using class based view
    path("", room_views.HomeView.as_view(), name="home"),  # 두번째 인자에는 함수만 들어갈 수 있다.
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path("login", views.LoginView.as_view(), name="login"),
    path("login/github", views.github_login, name="github-login"),
    path("login/github/callback", views.github_callback, name="github-callback"),
    path("login/kakao", views.kakao_login, name="kakao-login"),
    path("login/kakao/callback", views.kakao_callback, name="kakao-callback"),
    path("logout", views.log_out, name="logout"),
    path("signup", views.SignUpView.as_view(), name="signup"),
    path("verify/<str:key>", views.complete_verification, name="complete_verification"),
]

templates/partials/nav.html
<a href="{% url "core:home" %}"> wansik's airbnb </a>



<ul>
    
    {% if user.is_authenticated %}
        <li><a href="{% url "users:logout" %}">Logout</a></li>
    {% else %}
        <li><a href="{% url "users:login" %}">Login</a></li>
        <li><a href="{% url "users:signup" %}">Sign Up</a></li>
    {% endif %}
        
    
</ul>

templates/partials/social_login.html
<div>
  <a href="{% url 'users:github-login' %}"> Continue with Github </a>

  <a href="{% url 'users:kakao-login' %}"> Continue with Kakao </a>
</div>