config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings  # 장고에서 settings.py를 import할 때는 이와 같은 방식으로 한다.
from django.conf.urls.static import static


urlpatterns = [
    path("", include("core.urls", namespace="core")),
    path("rooms/", include("rooms.urls", namespace="rooms")),
    path("users/", include("users.urls", namespace="users")),
    path("admin/", admin.site.urls),
]

# 개발 모드인지 확인하고, 파일을 제공한다. 아닌 경우는 보안상 하면 안돼
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # settings.MEDIA_URL(media)로 요청이 들어오면, settings.MEDIA_ROOT(/uploads)로 보낸다.

core/urls.py
from django.urls import path
from rooms import views as room_views

app_name = "core"

urlpatterns = [
    # path("", room_views.all_rooms, name="home"), # not using class based view
    path("", room_views.HomeView.as_view(), name="home"),  # 두번째 인자에는 함수만 들어갈 수 있다.
]

rooms/urls.py
from django.urls import path
from . import views

app_name = "rooms"

urlpatterns = [
    path("<int:pk>", views.RoomDetail.as_view(), name="detail"),
    path("search/", views.SearchView.as_view(), name="search"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block page_title %}{% endblock page_title %} | wansik's airbnb</title>
  </head>
  <body>


  <header>
    {% include "partials/nav.html" %}

    {% block search-bar %}
      <form method="get" action="{% url "rooms:search" %}">
        <input value="" name="city" placeholder="Search By City" />
      </form>
    {% endblock search-bar %}


  </header>

  <!-- content라는 block을 넣을 거야 -->
    {% block content %}
    {% endblock %}


    {% include "partials/footer.html" %}
    &copy; wansik
  </body>
</html>